// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShareBookApi.Context;

#nullable disable

namespace ShareBook.Migrations
{
    [DbContext(typeof(ShareBookContext))]
    [Migration("20231120204001_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShareBookApi.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Message = "hej",
                            ProfileId = 1,
                            Subject = "min första post"
                        },
                        new
                        {
                            Id = 2,
                            Message = "hej",
                            ProfileId = 1,
                            Subject = "min andra post"
                        },
                        new
                        {
                            Id = 3,
                            Message = "hej",
                            ProfileId = 1,
                            Subject = "min tredje post"
                        },
                        new
                        {
                            Id = 4,
                            Message = "hej hej",
                            ProfileId = 2,
                            Subject = "min allra första post"
                        },
                        new
                        {
                            Id = 5,
                            Message = "hej svej",
                            ProfileId = 2,
                            Subject = "min trökiga andra post"
                        });
                });

            modelBuilder.Entity("ShareBookApi.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Mitt namn är Jonathan",
                            Name = "Jonathan"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mitt namn är Johan",
                            Name = "Johan"
                        });
                });

            modelBuilder.Entity("ShareBookApi.Models.BlogPost", b =>
                {
                    b.HasOne("ShareBookApi.Models.Profile", null)
                        .WithMany("Posts")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShareBookApi.Models.Profile", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
